# Generated by Django 3.2.25 on 2025-09-02 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0137_auto_20250828_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CSV 匯入',
                'verbose_name_plural': 'CSV 匯入',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='enable_ppa',
            field=models.BooleanField(default=False, help_text='Whether to calculate and display PPA (Performance, Power, Area) metrics for Verilog problems.', verbose_name='enable PPA calculation'),
        ),
        migrations.AddField(
            model_name='problem',
            name='enable_waveform',
            field=models.BooleanField(default=False, help_text='Whether to process and display waveform files for Verilog problems.', verbose_name='enable waveform processing'),
        ),
        migrations.AddField(
            model_name='problem',
            name='ppa_maximum_fmax',
            field=models.FloatField(blank=True, help_text='Maximum Fmax frequency allowed in MHz. If set, submissions above this frequency will fail.', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='maximum PPA Fmax (MHz)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(blank=True, choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('PLE', 'PPA Limit Exceeded'), ('IR', 'Invalid Return'), ('RTE', 'Runtime Error'), ('CE', 'Compile Error'), ('IE', 'Internal Error'), ('SC', 'Short Circuited'), ('AB', 'Aborted')], db_index=True, default=None, max_length=3, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='submissiontestcase',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('PLE', 'PPA Limit Exceeded'), ('IR', 'Invalid Return'), ('RTE', 'Runtime Error'), ('CE', 'Compile Error'), ('IE', 'Internal Error'), ('SC', 'Short Circuited'), ('AB', 'Aborted')], max_length=3, verbose_name='status flag'),
        ),
    ]
