# Generated by Django 3.2.25 on 2025-09-08 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0138_add_verilog_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='f4pga_board',
            field=models.CharField(blank=True, choices=[('', '--------'), ('basys3', 'Basys3'), ('arty_a7_35t', 'Arty A7-35T'), ('arty_a7_100t', 'Arty A7-100T'), ('nexys4_ddr', 'Nexys 4 DDR'), ('nexys_video', 'Nexys Video'), ('zybo_z7', 'Zybo Z7')], help_text='Select F4PGA target board for FPGA synthesis.', max_length=20, verbose_name='F4PGA board'),
        ),
        migrations.AddField(
            model_name='problem',
            name='f4pga_target_fmax',
            field=models.FloatField(blank=True, help_text='Target Fmax frequency (higher is better).', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='F4PGA target Fmax (MHz)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='openlane_core_area_um2',
            field=models.FloatField(blank=True, help_text='Maximum core area (lower is better).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max core area'),
        ),
        migrations.AddField(
            model_name='problem',
            name='openlane_critical_path_ns',
            field=models.FloatField(blank=True, help_text='Maximum critical path delay (lower is better).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max critical path'),
        ),
        migrations.AddField(
            model_name='problem',
            name='openlane_pdk',
            field=models.CharField(blank=True, choices=[('', '--------'), ('sky130A', 'sky130A'), ('sky130B', 'sky130B'), ('gf180mcuC', 'gf180mcuC')], help_text='Select OpenLane PDK for ASIC synthesis.', max_length=20, verbose_name='OpenLane PDK'),
        ),
        migrations.AddField(
            model_name='problem',
            name='openlane_power_total',
            field=models.FloatField(blank=True, help_text='Maximum total power consumption (lower is better).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max total power'),
        ),
        migrations.AddField(
            model_name='problem',
            name='openlane_ppa_score',
            field=models.FloatField(blank=True, help_text='Target PPA score (higher is better).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='target PPA score'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='enable_ppa',
            field=models.BooleanField(default=False, help_text='Whether to calculate PPA metrics.', verbose_name='enable PPA calculation'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='enable_waveform',
            field=models.BooleanField(default=False, help_text='Whether to process and display waveform files.', verbose_name='enable waveform processing'),
        ),
    ]
