# Generated by Django 3.2.25 on 2025-09-09 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0139_edit_verilog_features'),
    ]

    operations = [
    # 移除重複的 ppa_maximum_fmax AddField，保留 0138 的 AddField
        migrations.AlterField(
            model_name='problem',
            name='f4pga_board',
            field=models.CharField(blank=True, choices=[('', '--------'), ('basys3', 'Basys3'), ('arty_a7_35t', 'Arty A7-35T'), ('arty_a7_100t', 'Arty A7-100T'), ('nexys4_ddr', 'Nexys 4 DDR'), ('nexys_video', 'Nexys Video'), ('zybo_z7', 'Zybo Z7')], default='', help_text='Select F4PGA target board for FPGA synthesis.', max_length=20, verbose_name='F4PGA board'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='openlane_pdk',
            field=models.CharField(blank=True, choices=[('', '--------'), ('sky130A', 'sky130A'), ('sky130B', 'sky130B'), ('gf180mcuC', 'gf180mcuC')], default='', help_text='Select OpenLane PDK for ASIC synthesis.', max_length=20, verbose_name='OpenLane PDK'),
        ),
    ]
