# Generated by Django 3.2.25 on 2025-09-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0141_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='enable_ppa',
            field=models.BooleanField(default=False, help_text='Whether to calculate PPA metrics.', verbose_name='enable PPA calculation'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='enable_waveform',
            field=models.BooleanField(default=False, help_text='Whether to process and display waveform files.', verbose_name='enable waveform processing'),
        ),
    ]
